language: node_js

node_js:
   - node # will use latest node

before_script: # commands to run before the build step
   - npm install -g ionic
   - npm install -g cordova 

script: # the build step
   - ionic cordova build android --aot

notifications:
  email: # only receive email when the build status changes (someone broke the build!) 
    on_failure: change
    on_success: change   